---
- name: Define cluster hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Define master and workers
      add_host:
        name: k8s-master-01
        ansible_host: 192.168.0.109
        ansible_ssh_user: root
        ansible_ssh_pass: "0000"
        ansible_become: yes
        ansible_become_pass: "0000"

    - name: Define worker-01
      add_host:
        name: k8s-worker-01
        ansible_host: 192.168.0.106
        ansible_ssh_user: root
        ansible_ssh_pass: "0000"
        ansible_become: yes
        ansible_become_pass: "0000"

    - name: Define worker-02
      add_host:
        name: k8s-worker-02
        ansible_host: 192.168.0.110
        ansible_ssh_user: root
        ansible_ssh_pass: "0000"
        ansible_become: yes
        ansible_become_pass: "0000"

    - name: Define worker-03
      add_host:
        name: k8s-worker-03
        ansible_host: 192.168.0.111
        ansible_ssh_user: root
        ansible_ssh_pass: "0000"
        ansible_become: yes
        ansible_become_pass: "0000"


- name: Join worker nodes to Kubernetes cluster
  hosts: 
    - k8s-worker-01
    - k8s-worker-02
    - k8s-worker-03
  become: yes
  tasks:
    - name: Read join command from master node
      ansible.builtin.slurp:
        src: /tmp/k8s_join_command.txt
      register: join_command_file
      delegate_to: k8s-master-01
    - name: Join worker to cluster
      ansible.builtin.shell: "{{ join_command_file.content | b64decode }}"
      when: join_command_file.content is defined
      args:
        creates: /etc/kubernetes/kubelet.conf
    - name: Wait for node to register
      ansible.builtin.wait_for:
        path: /etc/kubernetes/kubelet.conf
        timeout: 60
    - name: Verify node status from master
      ansible.builtin.shell: |
        kubectl get nodes {{ inventory_hostname }}
      register: node_status
      delegate_to: k8s-master-01
      retries: 10
      delay: 10
      until: node_status.rc == 0
    - name: Display join status
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} joined successfully"
