---
- name: Add hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Define hosts
      add_host:
        name: web-server-1
        ansible_host: 192.168.31.245
        ansible_ssh_user: web-server-1
        ansible_ssh_pass: "password"
        ansible_become: yes
        ansible_become_pass: "password"
- name: My First Ansible Playbook
  hosts: web-server-1
  become: yes
  tasks:
    

    - name: Install Nginx package
      package:
        name: nginx
        state: present

    - name: Start and Enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        content: "<h1>Hello from {{ ansible_hostname }}!</h1>"
        dest: /var/www/html/index.html
